/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import constants.ColorConstants;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import utils.CustomEventSource;
import static view.Utils.customizeButton;

/**
 *
 * @author Panagiotis Argyropoulos - pargyropoulos@gmail.com or
 * std154845@ac.eap.gr
 */
public class SettingsView extends javax.swing.JPanel {
    /**
     * Creates new form About
     */
    public SettingsView() {
        initComponents();
        for (var component : mainPanel.getComponents()) {
            if (component instanceof JButton) {
                JButton button = (JButton) component;
                customizeButton(button, ColorConstants.buttonBackgroundColor, ColorConstants.buttonHoverColor);
                button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));        
            }
        }        
    }

    public void addCloseButtonListener(ActionListener listener) {
        closelBtn.addActionListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        closelBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        grid3 = new javax.swing.JTable();
        universityName1 = new javax.swing.JTextField();
        closelBtn1 = new javax.swing.JButton();
        closelBtn2 = new javax.swing.JButton();
        editBtn1 = new javax.swing.JButton();
        editBtn2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        closelBtn.setBackground(new java.awt.Color(45, 45, 48));
        closelBtn.setForeground(new java.awt.Color(255, 255, 255));
        closelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cancel.png"))); // NOI18N
        closelBtn.setText("Close");
        closelBtn.setAlignmentY(0.0F);
        closelBtn.setFocusPainted(false);
        closelBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        closelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        closelBtn.setIconTextGap(32);
        closelBtn.setInheritsPopupMenu(true);
        closelBtn.setMargin(new java.awt.Insets(0, 30, 0, 0));
        closelBtn.setMaximumSize(new java.awt.Dimension(200, 50));
        closelBtn.setMinimumSize(new java.awt.Dimension(200, 50));
        closelBtn.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel11.setText("Insert/Update/Delete country (search combo box):");

        deleteBtn.setBackground(new java.awt.Color(45, 45, 48));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete.png"))); // NOI18N
        deleteBtn.setAlignmentY(0.0F);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteBtn.setIconTextGap(0);
        deleteBtn.setInheritsPopupMenu(true);
        deleteBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        deleteBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        deleteBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        deleteBtn.setPreferredSize(new java.awt.Dimension(50, 50));

        addBtn.setBackground(new java.awt.Color(45, 45, 48));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/add.png"))); // NOI18N
        addBtn.setAlignmentY(0.0F);
        addBtn.setFocusPainted(false);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBtn.setIconTextGap(0);
        addBtn.setInheritsPopupMenu(true);
        addBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        addBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        addBtn.setPreferredSize(new java.awt.Dimension(50, 50));

        editBtn.setBackground(new java.awt.Color(45, 45, 48));
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/edit.png"))); // NOI18N
        editBtn.setAlignmentY(0.0F);
        editBtn.setFocusPainted(false);
        editBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editBtn.setIconTextGap(0);
        editBtn.setInheritsPopupMenu(true);
        editBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editBtn.setMaximumSize(new java.awt.Dimension(50, 50));
        editBtn.setMinimumSize(new java.awt.Dimension(50, 50));
        editBtn.setPreferredSize(new java.awt.Dimension(50, 50));

        grid3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        grid3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Country Name "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid3.setAlignmentX(0.0F);
        grid3.setAlignmentY(0.0F);
        grid3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grid3.setFocusable(false);
        grid3.setMinimumSize(new java.awt.Dimension(400, 600));
        grid3.setRowHeight(32);
        grid3.setSelectionBackground(new java.awt.Color(0, 120, 215));
        grid3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        grid3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid3.setShowGrid(false);
        grid3.getTableHeader().setResizingAllowed(false);
        grid3.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(grid3);

        universityName1.setToolTipText(null);
        universityName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName1FocusLost(evt);
            }
        });

        closelBtn1.setBackground(new java.awt.Color(45, 45, 48));
        closelBtn1.setForeground(new java.awt.Color(255, 255, 255));
        closelBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/save.png"))); // NOI18N
        closelBtn1.setText("Save");
        closelBtn1.setAlignmentY(0.0F);
        closelBtn1.setFocusPainted(false);
        closelBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        closelBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        closelBtn1.setIconTextGap(32);
        closelBtn1.setInheritsPopupMenu(true);
        closelBtn1.setMargin(new java.awt.Insets(0, 30, 0, 0));
        closelBtn1.setMaximumSize(new java.awt.Dimension(200, 50));
        closelBtn1.setMinimumSize(new java.awt.Dimension(200, 50));
        closelBtn1.setPreferredSize(new java.awt.Dimension(200, 50));

        closelBtn2.setBackground(new java.awt.Color(45, 45, 48));
        closelBtn2.setForeground(new java.awt.Color(255, 255, 255));
        closelBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete.png"))); // NOI18N
        closelBtn2.setText("Clear DB");
        closelBtn2.setAlignmentY(0.0F);
        closelBtn2.setFocusPainted(false);
        closelBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        closelBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        closelBtn2.setIconTextGap(32);
        closelBtn2.setInheritsPopupMenu(true);
        closelBtn2.setMargin(new java.awt.Insets(0, 30, 0, 0));
        closelBtn2.setMaximumSize(new java.awt.Dimension(200, 50));
        closelBtn2.setMinimumSize(new java.awt.Dimension(200, 50));
        closelBtn2.setPreferredSize(new java.awt.Dimension(200, 50));

        editBtn1.setBackground(new java.awt.Color(45, 45, 48));
        editBtn1.setForeground(new java.awt.Color(255, 255, 255));
        editBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/okIcon.png"))); // NOI18N
        editBtn1.setAlignmentY(0.0F);
        editBtn1.setFocusPainted(false);
        editBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editBtn1.setIconTextGap(0);
        editBtn1.setInheritsPopupMenu(true);
        editBtn1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editBtn1.setMaximumSize(new java.awt.Dimension(50, 50));
        editBtn1.setMinimumSize(new java.awt.Dimension(50, 50));
        editBtn1.setPreferredSize(new java.awt.Dimension(50, 50));

        editBtn2.setBackground(new java.awt.Color(45, 45, 48));
        editBtn2.setForeground(new java.awt.Color(255, 255, 255));
        editBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/okIcon.png"))); // NOI18N
        editBtn2.setAlignmentY(0.0F);
        editBtn2.setFocusPainted(false);
        editBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editBtn2.setIconTextGap(0);
        editBtn2.setInheritsPopupMenu(true);
        editBtn2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editBtn2.setMaximumSize(new java.awt.Dimension(50, 50));
        editBtn2.setMinimumSize(new java.awt.Dimension(50, 50));
        editBtn2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(universityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(closelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(editBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closelBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void universityName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName1FocusGained

    private void universityName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton closelBtn;
    private javax.swing.JButton closelBtn1;
    private javax.swing.JButton closelBtn2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton editBtn2;
    private javax.swing.JTable grid3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField universityName1;
    // End of variables declaration//GEN-END:variables
}
