/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import constants.ColorConstants;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import constants.ColorConstants;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import HTTP.WebData;
import java.awt.Color;
import repository.University;
import javax.swing.*;
/**
 *
 * @author tasos
 */
public class UniRecDialogView extends javax.swing.JDialog {

    /**
     * Creates new form uniRec
     * @param parent
     * @param modal
     */
    public UniRecDialogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (var component : mainPanel.getComponents()) {
            if (component instanceof JButton) {
                JButton button = (JButton) component;
                view.Utils.customizeButton(button, ColorConstants.buttonBackgroundColor,ColorConstants.buttonHoverColor);
                button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 1));        
            }
        }        
        
    }
    
    public void addExitButtonListener(ActionListener listener) {
            exitBtn.addActionListener(listener);
    }
    
    public void setUniversityData(WebData universityData) {
         if (universityData != null) {
            universityName.setText(universityData.getName());
//            universityName.setEditable(false);
            // ισως να του αλλάξω χρώμα
            //universityName.setBackground(Color.LIGHT_GRAY);
//            universityName.setBorder(null);
            
            universityName2.setText(universityData.getCountry());
            universityName1.setText(universityData.getAlpha_two_code());
            //universityName3.setText(universityData.getDescription());  // Αν υπάρχει πεδίο περιγραφής
        }
    }
    
    
    // Για να γεμίσει το Grid -> gridDomains
    public void populateDomainsGrid(List<String> domains) {
    // Ελέγχω αν η λίστα είναι κενή - ίσως να μην χρειαζεται, η τροποποιηση 
    // για εμφάνιση μήνυμα λάθους
        if (domains == null || domains.isEmpty()) {
            System.out.println("No domains to display.");
            return;
        }
    // Παίρνουμε το μοντέλο του πίνακα
        DefaultTableModel model = (DefaultTableModel) gridDomains.getModel();
    // Καθαρίζουμε τα προηγούμενα δεδομένα του πίνακα
        model.setRowCount(0);
    // Προσθέτουμε κάθε domain ως νέα γραμμή στον πίνακα
        for (String domain : domains) {
            model.addRow(new Object[]{domain});
        }
    }  
    // Όμοια για grid -> gridWebPages
    public void populateWebPagesGrid(List<String> webPages) { 
        if(webPages == null || webPages.isEmpty()){
            System.out.println("No Web Pages  to display.");
            return;
        }
        
        // Παίρνουμε το μοντέλο του πίνακα
        DefaultTableModel model = (DefaultTableModel) gridWebPages.getModel();
    // Καθαρίζουμε τα προηγούμενα δεδομένα του πίνακα
        model.setRowCount(0);
    // Προσθέτουμε κάθε domain ως νέα γραμμή στον πίνακα
        for (String webPage : webPages) {
            model.addRow(new Object[]{webPage});
        }
    
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        gridWebPages = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        gridDomains = new javax.swing.JTable();
        universityName1 = new javax.swing.JTextField();
        universityName2 = new javax.swing.JTextField();
        universityName3 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        grid3 = new javax.swing.JTable();
        universityName4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exitBtn1 = new javax.swing.JButton();
        exitBtn2 = new javax.swing.JButton();
        exitBtn4 = new javax.swing.JButton();
        universityName6 = new javax.swing.JTextField();
        exitBtn3 = new javax.swing.JButton();
        exitBtn8 = new javax.swing.JButton();
        exitBtn9 = new javax.swing.JButton();
        universityName8 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        grid4 = new javax.swing.JTable();
        universityName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("University");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Name:");

        jLabel2.setText("Country:");

        jLabel4.setText("Alpha-two-code:");

        jLabel7.setText("Description:");

        editBtn.setBackground(new java.awt.Color(45, 45, 48));
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cancel.png"))); // NOI18N
        editBtn.setText("Cancel");
        editBtn.setAlignmentY(0.0F);
        editBtn.setFocusPainted(false);
        editBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editBtn.setIconTextGap(32);
        editBtn.setInheritsPopupMenu(true);
        editBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        editBtn.setMaximumSize(new java.awt.Dimension(200, 50));
        editBtn.setMinimumSize(new java.awt.Dimension(200, 50));
        editBtn.setPreferredSize(new java.awt.Dimension(200, 50));

        saveBtn.setBackground(new java.awt.Color(45, 45, 48));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/okIcon.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setAlignmentY(0.0F);
        saveBtn.setFocusPainted(false);
        saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        saveBtn.setIconTextGap(32);
        saveBtn.setInheritsPopupMenu(true);
        saveBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        saveBtn.setMaximumSize(new java.awt.Dimension(200, 50));
        saveBtn.setMinimumSize(new java.awt.Dimension(200, 50));
        saveBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/logout.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setAlignmentY(0.0F);
        exitBtn.setFocusPainted(false);
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exitBtn.setIconTextGap(32);
        exitBtn.setInheritsPopupMenu(true);
        exitBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn.setMaximumSize(new java.awt.Dimension(200, 50));
        exitBtn.setMinimumSize(new java.awt.Dimension(200, 50));
        exitBtn.setPreferredSize(new java.awt.Dimension(200, 50));

        gridWebPages.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gridWebPages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Web Pages"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridWebPages.setAlignmentX(0.0F);
        gridWebPages.setAlignmentY(0.0F);
        gridWebPages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridWebPages.setFocusable(false);
        gridWebPages.setMinimumSize(new java.awt.Dimension(400, 600));
        gridWebPages.setRowHeight(32);
        gridWebPages.setSelectionBackground(new java.awt.Color(0, 120, 215));
        gridWebPages.setSelectionForeground(new java.awt.Color(255, 255, 255));
        gridWebPages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gridWebPages.setShowGrid(false);
        gridWebPages.getTableHeader().setResizingAllowed(false);
        gridWebPages.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(gridWebPages);

        gridDomains.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gridDomains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Domains"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridDomains.setAlignmentX(0.0F);
        gridDomains.setAlignmentY(0.0F);
        gridDomains.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridDomains.setFocusable(false);
        gridDomains.setMinimumSize(new java.awt.Dimension(400, 600));
        gridDomains.setRowHeight(32);
        gridDomains.setSelectionBackground(new java.awt.Color(0, 120, 215));
        gridDomains.setSelectionForeground(new java.awt.Color(255, 255, 255));
        gridDomains.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gridDomains.setShowGrid(false);
        gridDomains.getTableHeader().setResizingAllowed(false);
        gridDomains.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(gridDomains);
        if (gridDomains.getColumnModel().getColumnCount() > 0) {
            gridDomains.getColumnModel().getColumn(0).setHeaderValue("Domains");
        }

        universityName1.setBackground(new java.awt.Color(60, 63, 65));
        universityName1.setToolTipText(null);
        universityName1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        universityName1.setEnabled(false);
        universityName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName1FocusLost(evt);
            }
        });

        universityName2.setBackground(new java.awt.Color(60, 63, 65));
        universityName2.setToolTipText(null);
        universityName2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        universityName2.setEnabled(false);
        universityName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName2FocusLost(evt);
            }
        });

        universityName3.setToolTipText(null);
        universityName3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName3FocusLost(evt);
            }
        });

        grid3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        grid3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Schools"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid3.setAlignmentX(0.0F);
        grid3.setAlignmentY(0.0F);
        grid3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grid3.setFocusable(false);
        grid3.setMinimumSize(new java.awt.Dimension(400, 600));
        grid3.setRowHeight(32);
        grid3.setSelectionBackground(new java.awt.Color(0, 120, 215));
        grid3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        grid3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid3.setShowGrid(false);
        grid3.getTableHeader().setResizingAllowed(false);
        grid3.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(grid3);

        universityName4.setToolTipText(null);
        universityName4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName4FocusLost(evt);
            }
        });

        jLabel5.setText("Info:");

        exitBtn1.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn1.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/edit.png"))); // NOI18N
        exitBtn1.setAlignmentY(0.0F);
        exitBtn1.setFocusPainted(false);
        exitBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn1.setIconTextGap(0);
        exitBtn1.setInheritsPopupMenu(true);
        exitBtn1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn1.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn1.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn1.setPreferredSize(new java.awt.Dimension(50, 50));

        exitBtn2.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn2.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/add.png"))); // NOI18N
        exitBtn2.setAlignmentY(0.0F);
        exitBtn2.setFocusPainted(false);
        exitBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn2.setIconTextGap(0);
        exitBtn2.setInheritsPopupMenu(true);
        exitBtn2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn2.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn2.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn2.setPreferredSize(new java.awt.Dimension(50, 50));

        exitBtn4.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn4.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete.png"))); // NOI18N
        exitBtn4.setAlignmentY(0.0F);
        exitBtn4.setFocusPainted(false);
        exitBtn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn4.setIconTextGap(0);
        exitBtn4.setInheritsPopupMenu(true);
        exitBtn4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn4.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn4.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn4.setPreferredSize(new java.awt.Dimension(50, 50));

        universityName6.setToolTipText(null);
        universityName6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName6FocusLost(evt);
            }
        });

        exitBtn3.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn3.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/edit.png"))); // NOI18N
        exitBtn3.setAlignmentY(0.0F);
        exitBtn3.setFocusPainted(false);
        exitBtn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn3.setIconTextGap(0);
        exitBtn3.setInheritsPopupMenu(true);
        exitBtn3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn3.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn3.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn3.setPreferredSize(new java.awt.Dimension(50, 50));

        exitBtn8.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn8.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/add.png"))); // NOI18N
        exitBtn8.setAlignmentY(0.0F);
        exitBtn8.setFocusPainted(false);
        exitBtn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn8.setIconTextGap(0);
        exitBtn8.setInheritsPopupMenu(true);
        exitBtn8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn8.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn8.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn8.setPreferredSize(new java.awt.Dimension(50, 50));

        exitBtn9.setBackground(new java.awt.Color(45, 45, 48));
        exitBtn9.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete.png"))); // NOI18N
        exitBtn9.setAlignmentY(0.0F);
        exitBtn9.setFocusPainted(false);
        exitBtn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn9.setIconTextGap(0);
        exitBtn9.setInheritsPopupMenu(true);
        exitBtn9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exitBtn9.setMaximumSize(new java.awt.Dimension(50, 50));
        exitBtn9.setMinimumSize(new java.awt.Dimension(50, 50));
        exitBtn9.setPreferredSize(new java.awt.Dimension(50, 50));

        universityName8.setToolTipText(null);
        universityName8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityName8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityName8FocusLost(evt);
            }
        });

        grid4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        grid4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Departments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid4.setAlignmentX(0.0F);
        grid4.setAlignmentY(0.0F);
        grid4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        grid4.setFocusable(false);
        grid4.setMinimumSize(new java.awt.Dimension(400, 600));
        grid4.setRowHeight(32);
        grid4.setSelectionBackground(new java.awt.Color(0, 120, 215));
        grid4.setSelectionForeground(new java.awt.Color(255, 255, 255));
        grid4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid4.setShowGrid(false);
        grid4.getTableHeader().setResizingAllowed(false);
        grid4.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(grid4);

        universityName.setBackground(new java.awt.Color(60, 63, 65));
        universityName.setToolTipText(null);
        universityName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        universityName.setEnabled(false);
        universityName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                universityNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                universityNameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(universityName6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(universityName8))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(universityName2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(universityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(universityName)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(universityName3)
                                    .addComponent(universityName4, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(universityName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(universityName2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universityName3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(universityName4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(exitBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(exitBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(universityName8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(universityName6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(exitBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void universityName4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName4FocusLost

    private void universityName4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName4FocusGained

    private void universityName3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName3FocusLost

    private void universityName3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName3FocusGained

    private void universityName2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName2FocusLost

    private void universityName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName2FocusGained

    private void universityName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName1FocusLost

    private void universityName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName1FocusGained

    private void universityName6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName6FocusGained

    private void universityName6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName6FocusLost

    private void universityName8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName8FocusGained

    private void universityName8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityName8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityName8FocusLost

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void universityNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_universityNameFocusGained

    private void universityNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_universityNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_universityNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniRecDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniRecDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniRecDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniRecDialogView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UniRecDialogView dialog = new UniRecDialogView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JButton exitBtn2;
    private javax.swing.JButton exitBtn3;
    private javax.swing.JButton exitBtn4;
    private javax.swing.JButton exitBtn8;
    private javax.swing.JButton exitBtn9;
    private javax.swing.JTable grid3;
    private javax.swing.JTable grid4;
    private javax.swing.JTable gridDomains;
    private javax.swing.JTable gridWebPages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField universityName;
    private javax.swing.JTextField universityName1;
    private javax.swing.JTextField universityName2;
    private javax.swing.JTextField universityName3;
    private javax.swing.JTextField universityName4;
    private javax.swing.JTextField universityName6;
    private javax.swing.JTextField universityName8;
    // End of variables declaration//GEN-END:variables
}
